# Generated by Django 3.2.4 on 2023-06-12 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_contactform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactForm',
            new_name='Contact',
        ),
    ]
