# Generated by Django 3.2.4 on 2023-06-14 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_rename_contactform_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='youtube_links',
            field=models.URLField(default='https://www.youtube.com/'),
        ),
    ]
