# Generated by Django 3.2.4 on 2023-06-14 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_recipe_youtube_links'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='audio',
        ),
    ]
