# Generated by Django 3.2.4 on 2023-06-14 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_remove_recipe_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='youtube_links',
            field=models.CharField(default='', max_length=20),
        ),
    ]
