# Generated by Django 3.2.4 on 2023-06-15 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_alter_recipe_youtube_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='youtube_links',
            field=models.URLField(default=''),
        ),
    ]
