# Generated by Django 3.2.4 on 2023-06-15 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_alter_recipe_youtube_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='audio/'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='processtime',
            field=models.IntegerField(default=0),
        ),
    ]
