# Generated by Django 3.2.4 on 2023-07-03 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0014_auto_20230615_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.CharField(choices=[('veg', 'Vegetarian'), ('Non-veg', 'Non-Vegetarian'), ('Breakfast', 'Breakfast'), ('Snacks', 'Snacks'), ('Rice', 'Rice')], default='veg', max_length=20),
        ),
    ]
